### ISSUE TITLE
Wrong spelling of "OSSELOT_DEPLOYDIR" in README.md.

### ISSUE THREAD

**Issue by ingo2211** [iris-GmbH/meta-osselot#37]
In the README.md file, line 67 the variable `OSSELOT_DEPLOYDIR` (osselot.bbclass) is spelled `OSSELOT_DEPLOY_DIR`.

**Comment by Jasper-Ben** [comment]
Hi @ingo2211, thanks for reporting! I pushed a commit to all release branches to fix this :+1:
